### ISSUE TITLE
Order status is not changing

### ISSUE THREAD

**Issue by AaronTajriba** [myparcelnl/prestashop#207] opened 2022-12-13 15:38 UTC
### Module version

1.7.1

### PrestaShop version

1.7.8.7

### PHP version

7.4.33

### What went wrong?

Order status is not changed When "Order status when label scanned" or "Order status when delivered". You can see the settings in in the screenshots attached
![Scherm­afbeelding 2022-12-13 om 16 37 35](https://user-images.githubusercontent.com/70962249/207376982-7171c42f-747a-4cf3-942b-3bbf3bd3e682.png)
![Scherm­afbeelding 2022-12-13 om 16 37 59](https://user-images.githubusercontent.com/70962249/207377090-bfacb78a-7f81-43e6-85ed-b46db08f4f3a.png)

### Reproduction steps

Create an prestashop order and let it ship trough myparcelbe, you will see there is no updates when "the label is scanned" or when "delivered"

### Relevant log output

```shell
none
```

### Additional context

none

**Comment by EdieLemoine** [comment] 2022-12-13 15:51
Hi Aaron, could you check your logs to see if this may be a duplicate of #192?

**Comment by AaronTajriba** [comment] 2022-12-13 16:00
Hi Edie,

Thanks for your reply, however, i've already checked but this is not the case. There is no sign of any attempt of changing the order status. Extra info: I'm using the MyparcelBE module

**Comment by wthijmen** [comment] 2022-12-16 08:56
Hi @AaronTajriba,

I've tried to reproduce this steps but I'm not getting any fault at my environment with version 1.7.2 (https://github.com/myparcelnl/prestashop/releases/tag/v1.7.2). In this version it is working well after the label has been scanned and the status will change automatically at my side to shipped.

If the bug stays on you can write us at support@myparcel.nl

**Closed as completed by wthijmen** 2022-12-16 08:56 UTC
Labels: bug
