### ISSUE TITLE
The shipping price is shown (wrong) without VAT but is charged with VAT?

### ISSUE THREAD

**Issue by DerekVerheijen** [myparcelnl/prestashop#5] opened 2021-02-25 20:49 UTC
The shipping method shows first the right price incl. VAT but shifts from the incl VAT price to excl. VAT price.

PS: 1.7.7.0

![image](https://user-images.githubusercontent.com/56411378/109215256-33fcf800-77b3-11eb-9f6f-c267bbfde3ec.png)

**Comment by Mitchell-MyParcel** [comment] 2021-02-26 09:46
@DerekVerheijen : Does this happen consistently and simply after a refresh (f5)? I cannot reproduce this on our environment and we are using 1.7.7.1. I do not think an update to this version will solve the issue but you could try it. 

Since we cannot reproduce this (and if updating does not do the job) could you please mail us login credentials to your test environment so that we can have our developer take a look at it?

**Comment by Mitchell-MyParcel** [comment] 2021-05-18 15:38
Inmiddels kunnen we dit reproduceren. We gaan het oppakken. Zodra de fix beschikbaar is laten we het hier weten.

**Comment by Mitchell-MyParcel** [comment] 2021-06-09 07:28
@DerekVerheijen This is fixed in version 1.0.7.

**Closed by Mitchell-MyParcel** 2021-06-09 07:28 UTC
Labels: Next version, bug
